name: release

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on:
      - ubuntu-latest
    container:
      image: openjdk:11

    steps:
      - name: Install sbt
        run: |
          echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | tee /etc/apt/sources.list.d/sbt.list
          echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee /etc/apt/sources.list.d/sbt_old.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
          apt-get update
          apt-get install sbt
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Add safe.directory per https://github.com/actions/checkout/issues/766
      - name: Setting repo parent dir as safe safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Set CDC_VERSION
        id: set_version
        run: |
          CDC_VERSION=$(grep -oP 'version := "\K[^"-]+' version.sbt)
          echo "Set version value to github env file."
          echo "CDC_VERSION=$CDC_VERSION" >> $GITHUB_ENV
          echo "Enable output var"
          echo "::set-output name=CDC_VERSION::$CDC_VERSION"


      - name: Set git config and create new branch
        run: |
          echo "Set user.name=${{ github.actor }}"
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
    
          git checkout -b release_$CDC_VERSION

      # sbt-releaseを実行
      - name: Run sbt-release
        run: sbt "release with-defaults"

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "release_${{ steps.set_version.outputs.CDC_VERSION }}"
          destination_branch: "main"
          pr_title: "Release CDC pipeline to ${{ steps.set_version.outputs.CDC_VERSION }}"
          pr_body: "SSIA"
          github_token: ${{ secrets.GITHUB_TOKEN }}
